PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE ord (
ord_id INTEGER PRIMARY KEY,
ord TEXT NOT NULL,
ordklasse TEXT,
definisjon TEXT,
kommentar TEXT
);
INSERT INTO ord VALUES(3,'sol',NULL,NULL,NULL);
INSERT INTO ord VALUES(4,'måne',NULL,NULL,NULL);
COMMIT;
