-- Swadesh list
-- https://en.wikipedia.org/wiki/Swadesh_list#Swadesh_207_list

INSERT INTO concepts (id, desc, cat) VALUES
(1, 'I', 'person'),
(2, 'you (singular)', 'person'),
(3, 'he', 'person'),
(4, 'we', 'person'),
(5, 'you (plural)', 'person'),
(6, 'they', 'person'),
(7, 'this', 'demonstrative'),
(8, 'that', 'demonstrative'),
(9, 'here', 'place'),
(10, 'there', 'place'),
(11, 'who', 'question'),
(12, 'what', 'question'),
(13, 'where', 'question'),
(14, 'when', 'question'),
(15, 'how', 'question'),
(16, 'not', 'state'),
(17, 'all', 'quantity'),
(18, 'many', 'quantity'),
(19, 'some', 'quantity'),
(20, 'few', 'quantity'),
(21, 'other', 'quantity'),
(22, 'one', 'number'),
(23, 'two', 'number'),
(24, 'three', 'number'),
(25, 'four', 'number'),
(26, 'five', 'number'),
(27, 'big', 'physical state'),
(28, 'long', 'physical state'),
(29, 'wide', 'physical state'),
(30, 'thick', 'physical state'),
(31, 'heavy', 'physical state'),
(32, 'small', 'physical state'),
(33, 'short', 'physical state'),
(34, 'narrow', 'physical state'),
(35, 'thin', 'physical state'),
(36, 'woman', 'person'),
(37, 'man (adult male)', 'person'),
(38, 'man (human being)', 'person'),
(39, 'child', 'person'),
(40, 'wife', 'person'),
(41, 'husband', 'person'),
(42, 'mother', 'person'),
(43, 'father', 'person'),
(44, 'animal', 'animal'),
(45, 'fish', 'animal'),
(46, 'bird', 'animal'),
(47, 'dog', 'animal'),
(48, 'louse', 'animal'),
(49, 'snake', 'animal'),
(50, 'worm', 'animal'),
(51, 'tree', 'plant'),
(52, 'forest', 'place'),
(53, 'stick', 'object'),
(54, 'fruit', 'food'),
(55, 'seed', 'plant'),
(56, 'leaf', 'plant'),
(57, 'root', 'plant'),
(58, 'bark (of a tree)', 'plant'),
(59, 'flower', 'plant'),
(60, 'grass', 'plant'),
(61, 'rope', 'object'),
(62, 'skin', 'body part'),
(63, 'meat', 'food'),
(64, 'blood', 'body part'),
(65, 'bone', 'body part'),
(66, 'fat (noun)', 'body part'),
(67, 'egg', 'food'),
(68, 'horn', 'body part'),
(69, 'tail', 'body part'),
(70, 'feather', 'body part'),
(71, 'hair', 'body part'),
(72, 'head', 'body part'),
(73, 'ear', 'body part'),
(74, 'eye', 'body part'),
(75, 'nose', 'body part'),
(76, 'mouth', 'body part'),
(77, 'tooth', 'body part'),
(78, 'tongue (organ)', 'body part'),
(79, 'fingernail', 'body part'),
(80, 'foot', 'body part'),
(81, 'leg', 'body part'),
(82, 'knee', 'body part'),
(83, 'hand', 'body part'),
(84, 'wing', 'body part'),
(85, 'belly', 'body part'),
(86, 'guts', 'body part'),
(87, 'neck', 'body part'),
(88, 'back', 'body part'),
(89, 'breast', 'body part'),
(90, 'heart', 'body part'),
(91, 'liver', 'body part'),
(92, 'to drink', 'consumption action'),
(93, 'to eat', 'consumption action'),
(94, 'to bite', 'physical action'),
(95, 'to suck', 'physical action'),
(96, 'to spit', 'physical action'),
(97, 'to vomit', 'physical action'),
(98, 'to blow', 'physical action'),
(99, 'to breathe', 'physical action'),
(100, 'to laugh', 'social action'),
(101, 'to see', 'sensory action'),
(102, 'to hear', 'sensory action'),
(103, 'to know', 'mental action'),
(104, 'to think', 'mental action'),
(105, 'to smell', 'sensory action'),
(106, 'to fear', 'mental state'),
(107, 'to sleep', 'physical action'),
(108, 'to live', 'physical action'),
(109, 'to die', 'physical action'),
(110, 'to kill', 'social action'),
(111, 'to fight', 'social action'),
(112, 'to hunt', 'social action'),
(113, 'to hit', 'physical action'),
(114, 'to cut', 'physical action'),
(115, 'to split', 'physical action'),
(116, 'to stab', 'physical action'),
(117, 'to scratch', 'physical action'),
(118, 'to dig', 'physical action'),
(119, 'to swim', 'physical action'),
(120, 'to fly', 'physical action'),
(121, 'to walk', 'physical action'),
(122, 'to come', 'physical action'),
(123, 'to lie (as in a bed)', 'physical action'),
(124, 'to sit', 'physical action'),
(125, 'to stand', 'physical action'),
(126, 'to turn (intransitive)', 'physical action'),
(127, 'to fall', 'physical action'),
(128, 'to give', 'social action'),
(129, 'to hold', 'physical action'),
(130, 'to squeeze', 'physical action'),
(131, 'to rub', 'physical action'),
(132, 'to wash', 'physical action'),
(133, 'to wipe', 'physical action'),
(134, 'to pull', 'physical action'),
(135, 'to push', 'physical action'),
(136, 'to throw', 'physical action'),
(137, 'to tie', 'physical action'),
(138, 'to sew', 'physical action'),
(139, 'to count', 'mental action'),
(140, 'to say', 'social action'),
(141, 'to sing', 'social action'),
(142, 'to play', 'social action'),
(143, 'to float', 'physical action'),
(144, 'to flow', 'physical action'),
(145, 'to freeze', 'physical action'),
(146, 'to swell', 'physical action'),
(147, 'sun', 'nature'),
(148, 'moon', 'nature'),
(149, 'star', 'nature'),
(150, 'water', 'nature'),
(151, 'rain', 'nature'),
(152, 'river', 'nature'),
(153, 'lake', 'nature'),
(154, 'sea', 'nature'),
(155, 'salt', 'substance'),
(156, 'stone', 'object'),
(157, 'sand', 'substance'),
(158, 'dust', 'substance'),
(159, 'earth', 'nature'),
(160, 'cloud', 'nature'),
(161, 'fog', 'nature'),
(162, 'sky', 'nature'),
(163, 'wind', 'nature'),
(164, 'snow', 'nature'),
(165, 'ice', 'nature'),
(166, 'smoke', 'substance'),
(167, 'fire', 'nature'),
(168, 'ash', 'substance'),
(169, 'to burn', 'physical action'),
(170, 'road', 'place'),
(171, 'mountain', 'place'),
(172, 'red', 'property'),
(173, 'green', 'property'),
(174, 'yellow', 'property'),
(175, 'white', 'property'),
(176, 'black', 'property'),
(177, 'night', 'time'),
(178, 'day', 'time'),
(179, 'year', 'time'),
(180, 'warm', 'physical state'),
(181, 'cold', 'physical state'),
(182, 'full', 'quantitative state'),
(183, 'new', 'temporal state'),
(184, 'old', 'temporal state'),
(185, 'good', 'qualitative state'),
(186, 'bad', 'qualitative state'),
(187, 'rotten', 'qualitative state'),
(188, 'dirty', 'qualitative state'),
(189, 'straight', 'physical state'),
(190, 'round', 'physical state'),
(191, 'sharp (as a knife)', 'physical state'),
(192, 'dull (as a knife)', 'physical state'),
(193, 'smooth', 'physical state'),
(194, 'wet', 'physical state'),
(195, 'dry', 'physical state'),
(196, 'correct', 'qualitative state'),
(197, 'near', 'physical state'),
(198, 'far', 'physical state'),
(199, 'right', 'direction'),
(200, 'left', 'direction'),
(201, 'at', 'relation'),
(202, 'in', 'relation'),
(203, 'with', 'relation'),
(204, 'and', 'relation'),
(205, 'if', 'relation'),
(206, 'because', 'relation'),
(207, 'name', 'concept');